### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by perliedman** [jacobtoye/Leaflet.iconlabel#14]
Hi,
looking through this repo, I couldn't find a license. Would be nice to make it clear what license actually applies, since I'm about to bundle a slightly modified version - something I would not be allowed to do under the default copyright laws, if I understand correctly.

**Comment by jacobtoye** [comment]
Sorry mate, I've added one. If you haven't seen [Leaflet.label](https://github.com/Leaflet/Leaflet.label), I maintain this one more frequently.
